### ISSUE TITLE
Cluster cluster-name, that is provided in the prisma.yml could not be found

### ISSUE THREAD

**Issue by maxdarque** [graphcool/prisma-cloud-feedback#47]
I've successfully created a db on AWS RDS and have created a new cluster in a new workspace.

I then deployed to Prisma Cloud after which I tried to start my local `graphql-yoga` server with `yarn dev`.

I used the following formats in my `.env` file

```
PRISMA_ENDPOINT="https://cluster-name_workspace-name.prisma.sh/service-name/dev"
PRISMA_CLUSTER="workspace-name/cluster-name"
```

I get the following error.

```Cluster cluster-name, that is provided in the prisma.yml could not be found.```

Is it a configuration issue on my side?

I can see my cluster when I run `prisma cluster list`

**Comment by marktani** [comment]
We'll soon fix this problem. Please track this issue for the progress: https://github.com/graphcool/prisma/issues/1964

**Comment by marktani** [comment]
This is now fixed in `prisma@1.2.7`. Thanks for raising this issue, @maxdarque!

**Comment by maxdarque** [comment]
@marktani I've upgraded to `prisma@1.2.7`. I deleted my old cluster in a new workspace. I created a new cluster in my personal workspace. I successfully executed the `prisma deploy` command. I can see the service in the GUI.

However I still get the same error on `yarn dev`

**Comment by marktani** [comment]
how does your package.json look like? Also, are you using the Playground in the browser?

**Comment by maxdarque** [comment]
Yes so `yarn dev` launches the playground and I think that's where it's getting stuck. It might be a config thing on my side

{
  "name": "",
  "license": "UNLICENSED",
  "scripts": {
    "local-start": "dotenv -- nodemon -e ts,graphql -x ts-node src/index.ts",
    "dev": "npm-run-all --parallel local-start playground",
    "debug": "dotenv -- nodemon -e ts,graphql -x ts-node --inspect src/index.ts",
    "playground": "graphql playground --port 5000",
    "build": "rimraf dist && tsc",
    "start": "node dist/index.js",
    "local-start-js": "dotenv -- node dist/index.js"
  },
  "dependencies": {
    "aws-sdk": "^2.186.0",
    "bcryptjs": "2.4.3",
    "graphql-yoga": "^1.2.3",
    "isomorphic-fetch": "^2.2.1",
    "jsonwebtoken": "8.1.1",
    "moment": "^2.20.1",
    "prisma-binding": "^1.5.5"
  },
  "devDependencies": {
    "@types/bcryptjs": "2.4.1",
    "@types/isomorphic-fetch": "^0.0.34",
    "@types/validator": "^6.3.0",
    "dotenv-cli": "1.4.0",
    "graphql-cli": "2.12.4",
    "nodemon": "1.14.11",
    "npm-run-all": "4.1.2",
    "prisma": "1.2.7",
    "rimraf": "2.6.2",
    "ts-node": "4.1.0",
    "typescript": "2.6.2"
  }
}

**Comment by marktani** [comment]
@maxdarque, can you try with these dependencies instead:

```
{
  "name": "",
  "license": "UNLICENSED",
  "scripts": {
    "local-start": "dotenv -- nodemon -e ts,graphql -x ts-node src/index.ts",
    "dev": "npm-run-all --parallel local-start playground",
    "debug": "dotenv -- nodemon -e ts,graphql -x ts-node --inspect src/index.ts",
    "playground": "graphql playground --port 5000",
    "build": "rimraf dist && tsc",
    "start": "node dist/index.js",
    "local-start-js": "dotenv -- node dist/index.js"
  },
  "dependencies": {
    "aws-sdk": "^2.186.0",
    "bcryptjs": "2.4.3",
    "graphql-yoga": "^1.4.3",
    "isomorphic-fetch": "^2.2.1",
    "jsonwebtoken": "8.1.1",
    "moment": "^2.20.1",
    "prisma-binding": "^1.5.15"
  },
  "devDependencies": {
    "@types/bcryptjs": "2.4.1",
    "@types/isomorphic-fetch": "^0.0.34",
    "@types/validator": "^6.3.0",
    "dotenv-cli": "1.4.0",
    "graphql-cli": "2.15.8",
    "nodemon": "1.14.11",
    "npm-run-all": "4.1.2",
    "prisma": "1.3.2",
    "rimraf": "2.6.2",
    "ts-node": "4.1.0",
    "typescript": "2.6.2"
  }
}
```

I updated `graphql-yoga`, `prisma-binding`, `prisma` and `graphql-cli`.

**Comment by timsuchanek** [comment]
This should be fixed by now, please reopen if still an issue.
